### ISSUE TITLE
Error: "Unable to parse response body into JSON: 10

### ISSUE THREAD

**Issue by robtesch** [lanlin/nylas-php#2]
Hi Lanlin,

I've hit a new issue, as described in the title. This is only happening on one account. If possible, would there be a way of simply ignoring if this error occurs on a single message, and move on to all the others? I have a feeling that for a single message the JSON is corrupt or something.

Thanks,

Rob

**Comment by lanlin** [comment]
I think it‘s nothing about json_decode, but the data responded from Nylas was invalid JSON.

In [Nylas's API docs](https://docs.nylas.com/reference#introduction), they said: 
![image](https://user-images.githubusercontent.com/3468024/55957679-7be70480-5c99-11e9-84ed-276be2da1ae8.png)

I have checked the content type from the response header, like this:
![image](https://user-images.githubusercontent.com/3468024/55957925-17787500-5c9a-11e9-861b-12b78230f488.png)

So, when it's not JSON, it will be returned directly without parsing.

And, "**Unable to parse response body into JSON: 10**" means that: 
the "**[JSON_ERROR_UTF16](https://www.php.net/manual/en/json.constants.php)**" error occurs.

The reason is single unpaired UTF-16 surrogate in Unicode escape contained in the JSON string passed to json_encode(). 

I will add a new config option which can be used to control the exception throws when decoding the responded body.

After it enabled, the body content will be returned directly without parsing when the json_decode error occurs.

**Comment by lanlin** [comment]
@robtesch try this https://github.com/lanlin/nylas-php/releases/tag/3.4.0

**Comment by robtesch** [comment]
@lanlin awesome! Thank you! Will give it a go ASAP and let you know (probably only on Sunday).

**Comment by robtesch** [comment]
@lanlin OK fantastic, I managed to use this config option to work around the issue of the invalid json response from nylas. Turns out it was only 1 message from 1 account that was causing the issue. I have now built a workaround where I simply request smaller and smaller batches of messages until I get only valid messages, then I increment the offset to skip the invalid message.

**Comment by lanlin** [comment]
@robtesch That's good.
